// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adjectives.sql

package store

import (
	"context"
)

const countAdjectives = `-- name: CountAdjectives :one
SELECT COUNT(*) FROM adjectives
`

func (q *Queries) CountAdjectives(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdjectives)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdjectiveByLemma = `-- name: GetAdjectiveByLemma :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time FROM adjectives
WHERE lemma = $1
`

func (q *Queries) GetAdjectiveByLemma(ctx context.Context, lemma string) (Adjective, error) {
	row := q.db.QueryRow(ctx, getAdjectiveByLemma, lemma)
	var i Adjective
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getRandomAdjective = `-- name: GetRandomAdjective :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time FROM adjectives
WHERE active
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomAdjective(ctx context.Context) (Adjective, error) {
	row := q.db.QueryRow(ctx, getRandomAdjective)
	var i Adjective
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const insertAdjective = `-- name: InsertAdjective :exec
INSERT INTO adjectives (lemma, inflections, source)
VALUES ($1, $2, $3)
ON CONFLICT (lemma, source) DO NOTHING
`

type InsertAdjectiveParams struct {
	Lemma       string `db:"lemma" json:"lemma"`
	Inflections []byte `db:"inflections" json:"inflections"`
	Source      string `db:"source" json:"source"`
}

func (q *Queries) InsertAdjective(ctx context.Context, arg InsertAdjectiveParams) error {
	_, err := q.db.Exec(ctx, insertAdjective, arg.Lemma, arg.Inflections, arg.Source)
	return err
}

const truncateAdjectives = `-- name: TruncateAdjectives :exec
TRUNCATE adjectives RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateAdjectives(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAdjectives)
	return err
}
