// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountNouns(ctx context.Context) (int64, error)
	GetRandomNoun(ctx context.Context) (Noun, error)
	InsertNoun(ctx context.Context, arg InsertNounParams) error
	TruncateNouns(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
