// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verbs.sql

package store

import (
	"context"
)

const countVerbs = `-- name: CountVerbs :one
SELECT COUNT(*) FROM verbs
`

func (q *Queries) CountVerbs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVerbs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRandomVerb = `-- name: GetRandomVerb :one
SELECT id, lemma, inflections, frames, source, source_id, register, frequency, active, vote_count, create_time, update_time FROM verbs
WHERE active
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomVerb(ctx context.Context) (Verb, error) {
	row := q.db.QueryRow(ctx, getRandomVerb)
	var i Verb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Frames,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getVerbByLemma = `-- name: GetVerbByLemma :one
SELECT id, lemma, inflections, frames, source, source_id, register, frequency, active, vote_count, create_time, update_time FROM verbs
WHERE lemma = $1
`

func (q *Queries) GetVerbByLemma(ctx context.Context, lemma string) (Verb, error) {
	row := q.db.QueryRow(ctx, getVerbByLemma, lemma)
	var i Verb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Frames,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const insertVerb = `-- name: InsertVerb :exec
INSERT INTO verbs (lemma, inflections, frames, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (lemma, source) DO NOTHING
`

type InsertVerbParams struct {
	Lemma       string `db:"lemma" json:"lemma"`
	Inflections []byte `db:"inflections" json:"inflections"`
	Frames      []byte `db:"frames" json:"frames"`
	Source      string `db:"source" json:"source"`
}

func (q *Queries) InsertVerb(ctx context.Context, arg InsertVerbParams) error {
	_, err := q.db.Exec(ctx, insertVerb,
		arg.Lemma,
		arg.Inflections,
		arg.Frames,
		arg.Source,
	)
	return err
}

const truncateVerbs = `-- name: TruncateVerbs :exec
TRUNCATE verbs RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateVerbs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateVerbs)
	return err
}
